export interface ProductDataPayload {
    id?: string,
    name: string;
    categoryId: string;
    brandId: string; 
    price: number;

    isSale?: boolean;
    isActive?: boolean;
    isHot?: boolean;
    totalView?: number;
    description?: string;
    image?: string;
    imageUrl?: string;
    descriptionSeo?: string;
    keywordSeo?: string;
    contentHTML?: string;
    contentMarkdown?: string;
    pay?: number;
    number?: number;
    totalRating?: number;
    totalNumber?: number;
    file?: any;
    sale?: number;
    createdAt?: string;
    updatedAt?: string;
    wideScreenId: string;
    resolutionId: string;
    technologyScreenId: string;
    filmRearCameraId: string;
    advancedShootingId: string;
    resolutionRearCameraId: string;
    resolutionFrontCameraId: string;
    videoCallId: string;
    operationSystemId: string;
    cpuId: string;
    gpuId: string;
    ramId: string;
    romId: string;
    sdCardId: string;
    bluetoothId: string;
    mobileNetworkId?: string;
    chargingPortId: string;
    networkConnectionId: string;
    simId: string;
    wifiId: string;
    gpsId: string;
    otherConnectId: string;
    batteryTypeId: string;
    batteryTechnologyId: string; 
    batteryCapacityId: string;
    designId: string;
    weightName: string;
    sizeName: string; 
    materialName: string;
    isFlashLight?: boolean;
}

// export interface ProductDataPayload {
//     id?: string,
//     name: string;
//     slug: string;
//     categoryId: string;
//     brandId: string; 
//     price: number;
//     authId: string;
//     isSale: boolean;
//     isActive: boolean;
//     isHot: boolean;
//     totalView: number;
//     description: string;
//     image: string;
//     imageUrl: string;
//     descriptionSeo: string;
//     keywordSeo: string;
//     contentHTML: string;
//     contentMarkdown: string;
//     pay: number;
//     number: number;
//     totalRating: number;
//     totalNumber: number;
//     file: any;
//     sale: number;
//     createdAt: string;
//     updatedAt: string;
//     wideScreenId: string;
//     resolutionId: string;
//     technologyScreenId: string;
//     filmRearCameraId: string;
//     advancedShootingId: string;
//     resolutionRearCameraId: string;
//     resolutionFrontCameraId: string;
//     videoCallId: string;
//     operationSystemId: string;
//     cpuId: string;
//     gpuId: string;
//     ramId: string;
//     romId: string;
//     sdCardId: string;
//     bluetoothId: string;
//     mobileNetworkId: string;
//     chargingPortId: string;
//     networkConnectionId: string;
//     simId: string;
//     wifiId: string;
//     gpsId: string;
//     otherConnectId: string;
//     batteryTypeId: string;
//     batteryTechnologyId: string; 
//     batteryCapacityId: string;
//     designId: string;
//     weightName: string;
//     sizeName: string; 
//     materialName: string;
//     isFlashLight: boolean;
// }