version: '3.8'
services:
  db:
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_demo
    ports:
      - '5433:5432'
    volumes:
      - ../be/nestjs/db:/var/lib/postgresql/data
    expose:
      - 5432

  # adminer:
  #   image: adminer
  #   # restart: always
  #   ports:
  #     - 8084:8080

  backend:
    build:
      context: ../be/nestjs
      dockerfile: Dockerfile
    # restart: always
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      # - URL_REACT=http://localhost
      # - DB_HOST=host.docker.internal
    ports:
      - 1328:1328
    expose:
      - 1328

  # mailtrap:
  #   image: eaudeweb/mailtrap
  #   ports:
  #     - 2525:80
  #   environment:
  #     - MT_PORT=2525
  #     # - SMTP_USERNAME=mailtrap
  #     # - SMTP_PASSWORD=mailtrap
  #   networks:
  #     - mailtrap-network

  nginx: 
    image: nginx:1.23.3
    # restart: always
    ports:
      - 80:80
    volumes:
      - ../fe/reactjs/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
# networks:
#   mailtrap-network: