version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_demo
    ports:
      - '5433:5432'
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080